services:
  - type: web
    name: grappl-video-backend
    env: node
    region: singapore
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: VITE_VIMEO_CLIENT_ID
        sync: false
      - key: VITE_VIMEO_CLIENT_SECRET
        sync: false
      - key: VITE_VIMEO_ACCESS_TOKEN
        sync: false
