services:
  - type: web
    name: grappl-video-backend
    env: node
    region: singapore
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: VIMEO_CLIENT_ID
        sync: false
      - key: VIMEO_CLIENT_SECRET
        sync: false
      - key: VIMEO_ACCESS_TOKEN
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
